sedu: required

services:
  - docker

before_install:
  - docker build -t aloka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aloka/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-551188626830"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_Key 
  secret_access_key: 
    secure: "$AWS_Secret_key"

    

